# Generated by Django 6.0.4 on 2026-06-18 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('occup', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('parents_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('hometown', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(max_length=100, null=True)),
                ('ID_proof', models.FileField(blank=True, null=True, upload_to='')),
                ('room', models.CharField(choices=[('1', '1:Balcony room'), ('2', '2:Back right room'), ('3', '3:Back left room'), ('4', '4:Top room')], null=True)),
                ('status', models.BooleanField(null=True)),
                ('joined_date', models.DateTimeField(blank=True, null=True)),
                ('leaving_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('room', models.IntegerField(null=True)),
                ('previous', models.IntegerField(db_default=0, default=0, null=True)),
                ('previous2', models.IntegerField(db_default=0, default=0, null=True)),
                ('previous3', models.IntegerField(db_default=0, default=0, null=True)),
                ('current', models.IntegerField()),
                ('current2', models.IntegerField()),
                ('current3', models.IntegerField(default=0)),
                ('diff', models.IntegerField()),
                ('diff2', models.IntegerField()),
                ('diff3', models.IntegerField(default=0)),
                ('amount', models.IntegerField()),
                ('amount2', models.IntegerField()),
                ('amount3', models.IntegerField()),
                ('amount4', models.IntegerField(default=0)),
                ('total', models.IntegerField()),
                ('remark1', models.TextField(blank=True, null=True)),
                ('remark2', models.TextField(blank=True, null=True)),
                ('remark3', models.TextField(blank=True, null=True)),
                ('bill_status', models.CharField(blank=True, choices=[('paid', 'Paid'), ('due', 'Due')], null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2026, 6, 18, 17, 44, 31, 409778))),
                ('tenant', models.ManyToManyField(blank=True, null=True, to='main.tenant')),
            ],
        ),
    ]
